services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend-portal-ong-ser-amor
    # Variáveis de ambiente padrão (podem ser sobrescritas)
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:3000}