services:
  frontend:
    build:
      target: base
    command: sleep infinity
    ports:
      - "${FRONTEND_PORT:-3001}:3000" # Mapeia porta interna 3000 para porta externa 3001
    volumes:
      - .:/usr/src/app # Volume para hot-reload do código
      # - /usr/src/app/node_modules # "Truque" para isolar o node_modules (comentado até ter package.json)
    environment:
      - NODE_ENV=development # Define o ambiente como desenvolvimento